In [15]:
import os
import csv
import pandas as pd

election_datacsv = os.path.join("..", "Resources","election_data.csv").replace('\\','/')

with open(election_datacsv) as election_sheet:
    
    electiondata_reader = csv.reader(election_sheet)
    heading = next(electiondata_reader)

election = pd.read_csv(election_datacsv)
election_df = pd.DataFrame(election)
election_df.head(20)

#print("Election Results")
#print("-------------------------------")

    Ballot ID     County                Candidate
0     1323913  Jefferson  Charles Casper Stockham
1     1005842  Jefferson  Charles Casper Stockham
2     1880345  Jefferson  Charles Casper Stockham
3     1600337  Jefferson  Charles Casper Stockham
4     1835994  Jefferson  Charles Casper Stockham
5     1772756  Jefferson  Charles Casper Stockham
6     1920023  Jefferson  Charles Casper Stockham
7     1040408  Jefferson  Charles Casper Stockham
8     1018414  Jefferson  Charles Casper Stockham
9     1361118  Jefferson  Charles Casper Stockham
10    1045722  Jefferson  Charles Casper Stockham
11    1006975  Jefferson  Charles Casper Stockham
12    1489642  Jefferson  Charles Casper Stockham
13    1456389  Jefferson  Charles Casper Stockham
14    1936969  Jefferson  Charles Casper Stockham
15    1356658  Jefferson  Charles Casper Stockham
16    1651667  Jefferson  Charles Casper Stockham
17    1833621  Jefferson  Charles Casper Stockham
18    1730001  Jefferson  Charles Casper Stockham
19    1059252  Jefferson  Charles Casper Stockham

In [2]:
# The total number of votes cast

total_votes = election_df["Ballot ID"].nunique()
print(f"Total Votes: {total_votes}")
print("--------------------------------")

Total Votes: 369711
--------------------------------

In [13]:
# The total number of votes each candidate won
# For Charles Casper Stockham, Diana DeGette and Raymon Anthony Doane
# The percentage of votes each candidate won

Full_amount_votes = election_df.groupby("Candidate")["Ballot ID"].nunique()
print(Full_amount_votes)

Candidate
Charles Casper Stockham     85213
Diana DeGette              272892
Raymon Anthony Doane        11606
Name: Ballot ID, dtype: int64

In [20]:
# The winner of the election based on popular vote

Winner = election_df["Candidate"]
print(Winner)

0         Charles Casper Stockham
1         Charles Casper Stockham
2         Charles Casper Stockham
3         Charles Casper Stockham
4         Charles Casper Stockham
                   ...
369706       Raymon Anthony Doane
369707       Raymon Anthony Doane
369708       Raymon Anthony Doane
369709       Raymon Anthony Doane
369710       Raymon Anthony Doane
Name: Candidate, Length: 369711, dtype: object

In [ ]:
# Create a dictionary from the row data and append to a list of all_passengers
#    all_passengers = []
#    for name, age, sex in results:
#        passenger_dict = {}
#        passenger_dict["name"] = name
#        passenger_dict["age"] = age
#        passenger_dict["sex"] = sex
#        all_passengers.append(passenger_dict)